# 调试模式
debug = false

#录像保存路径
save_path = "/root"

# 数据库
[database]
#路径
path = "/var/webrtc/webrtc.db3"
# 初始化数据库
initial = true

# 账号
[[database.account]]
no="1234567"
name = "张三"
password = "1234567"
level = "0"
enable = "1"

[[database.account]]
no="9999999"
name = "监控"
password = "9999999"
level = "1"
enable = "1"

# 密码
[password]
# 复杂密码检查
strict_mode = true
#最小长度
length = 8
#最少大写字母
upper = 1
#最少小写字母
lower = 1
#最少数字字符
digital = 1
#最少特殊字符
other = 1

# 应用
[app]
# 端口 http:80 https:443
port = 443
# 启用 https
https = true
# 日志输出位置 debug 模式下无效
log = "/var/log/webrtc.log"
# 资源文件位置
resource = "/var/webrtc/resources"
# 证书文件位置 http 模式下无效
[app.signature]
crt = "/var/webrtc/sign/cert.pem"
key = "/var/webrtc/sign/key.pem"
